spring:
  cache:
    caffeine:
      spec: expireAfterAccess=4320s,maximumSize=1000
  main:
    allow-bean-definition-overriding: true
  application:
    name: prueba-tecnica
  datasource:
    url: jdbc:h2:mem:pruebatecnicadatabase
    driverClassName: org.h2.Driver
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher